filter:
  excluded_paths:
    - tests/
  dependency_paths:
    - vendor/

build:
  nodes:
    coverage:
      environment:
        php: 7.2
      tests:
        override:
          - command: composer test
            coverage:
              file: build/clover.xml
              format: clover
